// Generated by ParserBuilder @ 19/05/2001 8:56:25 PM

program Delphi6TestHarness;

uses
  Forms,
  Delphi6TestHarness_Main in 'Delphi6TestHarness_Main.pas' {Form1},
  Win32OnlyComponent in 'Win32OnlyComponent.pas',
  Win32OnlyScanner in 'Win32OnlyScanner.pas',
  Win32OnlyParser in 'Win32OnlyParser.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end. (* Delphi6TestHarness *)