// Generated by ParserBuilder @ 27/05/2001 4:51:15 PM

program Win32OnlyTestHarness;

uses
  Forms,
  Win32OnlyTestHarness_Main in 'Win32OnlyTestHarness_Main.pas' {Form1};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end. (* Win32OnlyTestHarness *)